{
"customer_id" : 1,
`amount` : 100.00,
`type` : "DEPOSIT",
`transaction_id` : 1,
`description` : "deposit",
`currency_code` : "EUR",
`status` : "pending",
`method` : "online",
`reference_number` : "1234567890",
`source_account_number` : "1234567890",
`destination_account_number` : "0987654321",
`transaction_fee` : 0.00,
`balance_after_transaction`: 3000.00,
`authorized_by` : "bank_aut",
`created_date`
`last_modified_date`
}